include:
  #_____________________________________Body_____________________________________
  - ${ROOT_DIR}/body/docker-compose.yaml
  # _____________________________________SLAM________________________________________
  - ${ROOT_DIR}/SLAM/docker-compose.yaml
  # #_____________________________________Navigation__________________________________
  # - ${ROOT_DIR}/navigation/docker-compose.yaml
  # #_____________________________________Stuff_______________________________________
  # - ${ROOT_DIR}/stuff/docker-compose.yaml