/rgbd_sync:
  ros__parameters:
    compressed_rate: 0.0
    decimation: 1
    # Depth compatible types: compressedDepth (see "rosrun image_transport list_transports")
    depth_image_transport: raw
    depth_scale: 1.0
    diagnostic_updater:
      period: 2.0
      use_fqn: false
    # Common types: compressed, theora (see "rosrun image_transport list_transports")
    rgb_image_transport: raw