/rtabmap_viz:
  ros__parameters:
    # false=exact synchronization.
    camera_node_name: ''
    diagnostic_updater:
      period: 2.0
      use_fqn: false
    # Fixed frame id of the robot (base frame), you may set "base_link" or "base_footprint" if they are published. For camera-only config, this could be "camera_link".
    init_cache_path: ''
    is_rtabmap_paused: false
    max_odom_update_rate: 10.0
    # Sync odometry data from different sensors
    odom_sensor_sync: true
    # General QoS used for sensor input data: 0=system default, 1=Reliable, 2=Best Effort.
    qos_image: 1       # 0=system default, 1=Reliable, 2=Best Effort
    qos_odom: 1
    qos_scan: 1
    qos_sensor_data: 0
    qos_user_data: 0
    queue_size: -1
    rgbd_cameras: 1
    rtabmap: rtabmap