# ____________________________EXTENSTIONS___________________________
x-env_slam: &env
  environment:
    - "DISPLAY=$DISPLAY"
    - "NVIDIA_VISIBLE_DEVICES=all"
    - "NVIDIA_DRIVER_CAPABILITIES=all"
    #- "FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml"
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

x-vol: &vol
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ${ROOT_DIR:-/home/tms/Projects/black_plat}/data:/data

x-deploy: &deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
# ____________________________SERVICES___________________________
services:
  lio-sam:
    build:
      context: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/LIO_SAM/
      dockerfile: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/LIO_SAM/docker/Dockerfile
      additional_contexts:
        t21-rviz2: "service:rviz2"
    develop:
      watch:
        - action: rebuild
          path: ./SLAM/LIO_SAM/ros2
          target: /ros2_ws/src
          ignore:
            - config/
        - action: sync+restart
          path: SLAM/LIO_SAM/config
          target: /ros2_ws/src/config
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    <<: [*env, *vol, *deploy]
    pre_stop:
      - command: # TODO command to save map
    command: ros2 launch lio_sam run.launch.py
  lego-loam:
    build:
      context: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/LeGO-LOAM-ROS2/
      dockerfile: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/LeGO-LOAM-ROS2/docker/Dockerfile
      additional_contexts:
        t21-rviz2: "service:rviz2"
    develop:
      watch:
        - action: rebuild
          path: ./SLAM/LeGO-LOAM-ROS2/ros2
          target: /ros2_ws/src
          ignore:
            - LeGO-LOAM/config/
            - LICENSE
            - README.md
            - Shan_Englot_IROS_2018_Preprint.pdf
        - action: sync+restart
          path: ./SLAM/LeGO-LOAM-ROS2/ros2/LeGO-LOAM/config
          target: /ros2_ws/src/config
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    <<: [*env, *vol, *deploy]
    pre_stop:
    - command: # TODO command to save map
    command: ros2 launch lego_loam_sr run.launch.py
  cartographer:
    build:
      context: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/t21_cartographer/
      dockerfile: ${ROOT_DIR:-/home/tms/Projects/black_plat}/SLAM/t21_cartographer/docker/Dockerfile
      additional_contexts:
        t21-rviz2: "service:rviz2"
    develop:
      watch:
        - action: rebuild
          path: ./SLAM/t21_cartographer/ros2
          target: /ros2_ws/src
          ignore:
            - config/
            - README.md
        - action: sync+restart
          path: ./SLAM/t21_cartographer/ros2/config
          target: /ros2_ws/src/config
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    <<: [*env, *vol, *deploy]
    pre_stop:
      - command: # TODO command to save map
    command: ros2 launch t21_cartographer cartographer.launch.py