<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>t21_nav2</name>
  <version>0.0.0</version>
  <description>Platform Nav2 Package</description>
  <maintainer email="TODO@yandex.ru">TODO</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>slam_toolbox</depend>
  <depend>nav2_navfn_planner</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
